openapi: 3.0.0
info:
  version: 1.0.0
  title: Contact book
  description: This is contact book
tags:
  - name: Contacts
    description: Operation with contacts
servers:
  - url: https://nodejs-hw-mongodb-7-wywt.onrender.com
  - url: http://127.0.0.1:8080
paths:
  /contacts/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        description: Contact ID
    get:
      $ref: './docs/swagger/paths/contacts/{id}/get.yaml'
    patch:
      $ref: './docs/swagger/paths/contacts/{id}/patch.yaml'
    delete:
      $ref: './docs/swagger/paths/contacts/{id}/delete.yaml'

  /contacts:
    get:
      $ref: './docs/swagger/paths/contacts/get.yaml'
    post:
      $ref: './docs/swagger/paths/contacts/post.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
